# Configuração básica do site
title: "Deep Learning Aplicado ao Sensoriamento Remoto"
description: "Curso avançado para mestrado e doutorado"
baseurl: "/curso_Deep_Learning_Aplicado_ao_Sensoriamento_Remoto"
url: "https://dsgoficial.github.io"

# Configuração do Jekyll
markdown: kramdown
highlighter: rouge

# Configuração do Kramdown para matemática
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  input: GFM
  auto_ids: true
  toc_levels: 1..3

source: .
destination: ./_site

# Plugins essenciais
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-toc
  - jekyll-last-modified-at

# Configuração de coleções para organizar o conteúdo
collections:
  modulos:
    output: true
    permalink: /:collection/:name/
  exercicios:
    output: true
    permalink: /:collection/:name/

# Configuração para código e matemática
defaults:
  - scope:
      path: ""
      type: "modulos"
    values:
      layout: "module"
      toc: true
  - scope:
      path: ""
      type: "exercicios"
    values:
      layout: "exercise"

# Configuração para GitHub Pages
github: [metadata]

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .bundle
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata